### ISSUE TITLE
Processed 0 Manga

### ISSUE THREAD

**Issue by rj452** [waicool20/mr2tachiyomi#10]
I'm using MacOs with Java 8 installed. I also used Helium to retrieved my Mangarock.db but it doesn't process anything.
[mr2tachiyomi.log](https://github.com/waicool20/mr2tachiyomi/files/3639468/mr2tachiyomi.log)

**Comment by waicool20** [comment]
Weird, how big is your db file? You can use this tool to actually check if your db is fine https://sqlitebrowser.org/dl/ , if you don't mind you can also send me a copy via email (see profile) privately or here for me to check

**Comment by rj452** [comment]
File size is 10.4mb. Sure! I'll upload it on my google drive and send it to you.

**Comment by waicool20** [comment]
Your favorites are empty in the database, did you sync them?
![image](https://user-images.githubusercontent.com/5538666/65384211-f3918300-dd51-11e9-971f-d2f576ebf4c3.png)

Edit: So is your read history

**Comment by rj452** [comment]
I did. I was also reading something before I made the backup.
![Screenshot_2019-09-22-16-00-42-707_com notabasement mangarock android lotus](https://user-images.githubusercontent.com/20613912/65384245-892d1280-dd52-11e9-81ec-3597f6836e28.png)

**Comment by waicool20** [comment]
I can only tell you to try syncing and then closing the app then, then swipe it away from app menu so it properly unloads from phone memory. Then try to back it up again.

If that doesn't work then you can try backing it up from a rooted emulator like Nox. 

Barring that I can't really help
