### ISSUE TITLE
I cannot find the "mangarock.db" file in the directory

### ISSUE THREAD

**Issue by mfernd** [waicool20/mr2tachiyomi#11]
Hello,
I want to copy the `mangarock.db` file from the `com.mangarock.mangarock.mangarock.mangarock.android.lotus/` directory, but I don't see any file or folder that resembles it.
Do you have any ideas?

A screenshot of my folder :
![image](https://user-images.githubusercontent.com/22498591/70192878-84df8700-16fd-11ea-8724-e08f286bf40b.png)

**Comment by waicool20** [comment]
Duplicate of #6, please refer to my reply over there.

 https://github.com/waicool20/mr2tachiyomi/issues/6
