### ISSUE TITLE
mr2tachiyomi.jar not responding

### ISSUE THREAD

**Issue by Nikskill** [waicool20/mr2tachiyomi#18]
When running the com.notabasement.mangarock.android.lotus.ab file with the mr2tachiyomi.jar file the program stops responding. It happens right after choosing where to save the .json file. I have restarted and tried to rerun with the same outcome. Not sure what else I should do to make it work. Let me know if I should include any more information

**Comment by waicool20** [comment]
If your backup is big, it takes quite amount of ram to decompress it, check if the ram usage goes up in task manager. If downloaded manga is being included with the backup you should disable that. Typical backup size is usually at most 100MB.

**Comment by Nikskill** [comment]
I think downloaded manga is probably being included in my current backup, since the .ab file is almost 2gb. Do you know how I can disable this when making another backup?

**Comment by waicool20** [comment]
It's been a while since I've used helium so I'm not sure, I think you will need to look that up yourself

**Comment by Nikskill** [comment]
Okay. I'll do that and let you know if that resolves my issue

**Comment by Nikskill** [comment]
I fixed it by redoing the backup after clearing the app data for mangarock and restoring favourites. Resulted in a much smaller .ab file which ran successfully
