### ISSUE TITLE
Conversion failed

### ISSUE THREAD

**Issue by Candy-Sama** [waicool20/mr2tachiyomi#19]
Hi Dev! I tried converting the file, but I got a conversion fail - here are the log details, please help! ><

[mr2tachiyomi.log](https://github.com/waicool20/mr2tachiyomi/files/4125617/mr2tachiyomi.log)

**Comment by waicool20** [comment]
How big is your backup?

**Comment by Candy-Sama** [comment]
85691kb, so.. 86MB? :?

**Comment by waicool20** [comment]
Hmm looks normal, can you send me the backup by email?

**Comment by Candy-Sama** [comment]
Hi waicool!

Here is the files as requested
 com.notabasement.mangarock.android.lotus.ab
<https://drive.google.com/file/d/1-fzpUOjEROqpjlZ6mVc64GcIvqx_2B5z/view?usp=drive_web>

**Comment by Candy-Sama** [comment]
sent!

**Comment by waicool20** [comment]
Seems like its a bad backup, only the manga images were backed up but not the actual manga database containing your favorites.

**Comment by Candy-Sama** [comment]
interesting, it told me it was backed up

**Comment by waicool20** [comment]
When it runs, there's usually a tar file that's extracted from the ab file, itself being a archive as well, inside there should be a file under `apps/com.notabasement.mangarock...../` called mangarock.db

**Comment by Candy-Sama** [comment]
I did another one, it successfully parsed thru except for specific sources, I'll manually find it via the log files. Quick check, I don't suppose it doesnt actually open up in tachiyomi right? Considering that Mangarock is now disabled in tachiyomi

**Comment by waicool20** [comment]
I guess you're not following [this guide on reddit](https://www.reddit.com/r/mangarockapp/comments/ekt2zo/how_to_migrate_from_manga_rock_to_tachiyomi/)? Just follow it to migrate your manga, if you don't migrate sources you definitely can't open it.

**Comment by Candy-Sama** [comment]
Nope, I came here thanks to someone in KanColle Reddit Discord so...

Thanks for the heads up and quick assistance tho!

Stay safe from the Wuhan Virus fellow Asian!
(Shit's hitting the fan here too)

**Comment by waicool20** [comment]
No problem :)
