### ISSUE TITLE
mr2tachiyomi not doing anything

### ISSUE THREAD

**Issue by zerokyko** [waicool20/mr2tachiyomi#20]
I have Java, and clicking your jar file does nothing. Command line doesn't work either. The link you provided to Java 8 is dead so I don't know if that's the problem since I have a different version of Java.

**Comment by waicool20** [comment]
Try the one here https://www.oracle.com/java/technologies/javase/javase-jdk8-downloads.html

**Comment by Josh12323** [comment]
I too am having trouble with this. I tried both jre and jdk, both x64 and x84, and java is properly added to my path. All I get when I run it is a flash of a command box for one split second. On windows 10 btw.

**Comment by waicool20** [comment]
Do you have other versions of java? Make sure you have a distribution of java that also has javafx, which oracle one does.

**Comment by Josh12323** [comment]
nevermind I'm dumb I just ran the file directly from command prompt with java -jar mr2tachiyomi.jar and it worked
