### ISSUE TITLE
Stuck on step 3

### ISSUE THREAD

**Issue by zethroree** [waicool20/mr2tachiyomi#21]
Hi, I'm stuck at step 3 for non-rooted device. How do I open MR2tachiyomi application jar? sorry I'm new to this

**Comment by waicool20** [comment]
Install java first, then double click the jar file and it should open up

**Comment by zethroree** [comment]
after I restore it in tachiyomi, all my mangas are shown as error, is there a fix around this?

this is the screenshot 
https://imgur.com/wnwAcid

**Comment by waicool20** [comment]
Are you following this [guide](https://www.reddit.com/r/mangarockapp/comments/ekt2zo/how_to_migrate_from_manga_rock_to_tachiyomi/)? Use the dummy mangarock source when you import

**Comment by zethroree** [comment]
Oh my goodness thank you so much, I didn't know this guide exist, I only followed the guide from tachiyomi and the guide from your readme. You save my life thanks man

**Comment by zethroree** [comment]
Hey, thanks man it's all migrated.

**Comment by waicool20** [comment]
No problem
