### ISSUE TITLE
Part 1 Between Step 5 and 6

### ISSUE THREAD

**Issue by roshanyadav29** [waicool20/mr2tachiyomi#22]
Hi, I am currently using a Android device and just can't seem to connect the mobile and Pc version of helium no matter how much i try. It just say "Waiting for Device" and does not connect. Already tried to follow the link below. Can u help me with it??

**Comment by SenzuaLab** [comment]
If a device does not connect you may need to download the ADB drivers, have you tried that yet?

**Comment by waicool20** [comment]
People have been getting better results with chrome version of helium, try that. Otherwise not much I can help about getting helium to work

**Comment by roshanyadav29** [comment]
> If a device does not connect you may need to download the ADB drivers, have you tried that yet?

I did but still doesn't work

**Comment by roshanyadav29** [comment]
> People have been getting better results with chrome version of helium, try that. Otherwise not much I can help about getting helium to work

Okay I'll try that
