### ISSUE TITLE
Issue with file

### ISSUE THREAD

**Issue by 532TeethAndCounting** [waicool20/mr2tachiyomi#25]
I am not sure if I am using the file correctly but this is what happened. When I downloaded the file and opened it with Java 8, I tried to press run but it wanted me to open something first so I opened the .ab file thinking this was what it wanted, but then when I pressed run it asked for anothher file but none came up for me to run. I figured I needed it to open something else so I could run the .ab file instead but I could't figure out what that thing was.

**Comment by waicool20** [comment]
Second dialog is for inputting the save file location

**Comment by 532TeethAndCounting** [comment]
I figured that it would be but it is asking me to select an existing file instead. Am I misunderstanding something?

**Comment by waicool20** [comment]
Just type in something like `tachiyomi.json` and save

**Comment by 532TeethAndCounting** [comment]
Thats where the issue is. I hit run and typed in DummyThicc.json because I'm bad at names and it said "DummyThicc is not a file name please select a file name." I was saving it to the phone if that changes anything.

**Comment by waicool20** [comment]
If you can take screenshots on where youre getting stuck then that would be great, just make sure were on the same page

**Comment by 532TeethAndCounting** [comment]
![Snip](https://user-images.githubusercontent.com/61371021/75104309-6f2b8080-55cd-11ea-9904-577a4f3efe72.PNG)
This is after I opened the .ab file and hit run

**Comment by joseph619** [comment]
Try another file name

**Comment by waicool20** [comment]
try adding the `.json` file to the file name also save to your pc first then move it over.

**Comment by 532TeethAndCounting** [comment]
That worked, thank you so much, I had no clue what I was doing wrong.
