### ISSUE TITLE
Step 8 : conversion failed

### ISSUE THREAD

**Issue by pikapikachuss** [waicool20/mr2tachiyomi#26]
When I do step 8, after running the .ab file, I can't get the .json file because of a "sql lite error or missiing database" 
![image](https://user-images.githubusercontent.com/61371270/75104121-84bc9c80-5605-11ea-8a3b-f3009f73f94c.png)

When I run though, I do get a .tar archive file and a .db file ^^'

**Comment by waicool20** [comment]
Check if you got a 0kb size .db file, if you do then its a bad backup. Delete your downloaded chapters, exit the app and clear cache then try backing up again.

**Comment by pikapikachuss** [comment]
yeah I do get a 0kb size .db file, but what do you mean "Delete your downloaded chapters, exit the app and clear cache then try backing up again." ? you mean : I delete all the files created by Helium on my phone, then exit helium, clear cache and redo the process to get a backup of mangarock?

**Comment by waicool20** [comment]
Delete the downloaded chapters in mangarock, they tend to interfere with the backup process because there is so much data. Exit mangarock. Clear mangarock cache. Backup again.

**Comment by pikapikachuss** [comment]
Okay thanks (sorry to be so dumb lol). I deleted the downloaded chapters but now I have an issue with Helium and the backup urg.. something about the password... I'll be back
