### ISSUE TITLE
Helium backup issue

### ISSUE THREAD

**Issue by shrlock616** [waicool20/mr2tachiyomi#27]
Hi, I cant backup MR on helium as there is always an error while performing the backup. I have cleared cache and deleted downloaded manga already as well.

**Comment by waicool20** [comment]
Use chromium extension, not much else I can give you tips with.

**Comment by shrlock616** [comment]
Sorry, can you elaborate how to use the extension?

**Comment by waicool20** [comment]
I havn't used the extension in quite a while, so you will need to do your own research sorry.
