### ISSUE TITLE
Tar file

### ISSUE THREAD

**Issue by jumyko** [waicool20/mr2tachiyomi#28]
When I name the output file as output.json, the file always comes out as com.notabasement.mangarock.android.lotus.tar, not as output.json. Renaming doesn't work and I don't know how to change the file to json, any ideas?

**Comment by waicool20** [comment]
That file is automatically generated, output.json probably got stored somewhere you didn't see, please check again

**Comment by jumyko** [comment]
I created a file for it specifically and it appeared, thanks for helping, much appreciated.
