### ISSUE TITLE
Add CSV export

### ISSUE THREAD

**Issue by Dudecake** [waicool20/mr2tachiyomi#3]
The format of the CSV would need to be chosen. The same format as the json would be the easiest but, depending on the intended use of the CSV, that might not suffice.

Is the same format as the json fine or did you have another format in mind?

**Comment by waicool20** [comment]
Major changes were made to the base code, you might want to update your PR to match, though csv export is not a really high priority for the tool right now. I want to re-implement and integrate the ab2tar tool first
