### ISSUE TITLE
Failed Conversion database

### ISSUE THREAD

**Issue by reddev94** [waicool20/mr2tachiyomi#30]
my conversion fail because of this error: Unsupported source: 2
here the log

[mr2tachiyomi.log](https://github.com/waicool20/mr2tachiyomi/files/4257503/mr2tachiyomi.log)

**Comment by waicool20** [comment]
Only mangarock/reader/eden are supported, if you mainly used some other source from that then youre out of luck.

**Comment by reddev94** [comment]
My source is mangaeden(ITA)....only eng is supported ?

**Comment by waicool20** [comment]
Yeah it's listed as a different source.

**Comment by reddev94** [comment]
Ok, so this is not an issue
