### ISSUE TITLE
MR2Tachiyomi Failing to open

### ISSUE THREAD

**Issue by RockRoller01** [waicool20/mr2tachiyomi#32]
When I try to run the programm nothing happens, besides an empty log file being created. I tried both double clicking and command line, but in both cases it didnt open.
Tried MR2Tachiyomi 1.4.0 and 1.2.0. 
WIn10, Java8 Update 221 (build 1.8.0_221-b11)

**Comment by waicool20** [comment]
How are you launching via command line? What's the output

**Comment by RockRoller01** [comment]
Apparently I slightly messed up the input. So its user fault
