### ISSUE TITLE
Invalid backup file

### ISSUE THREAD

**Issue by ghost** [waicool20/mr2tachiyomi#37]
Getting this error when trying to restore the backup
`Invalid backup file java.ioEOFException: End of input at line 61138 column 11 path $.mangas[328].chapters[15].r`

[mangarockbackups.zip](https://github.com/waicool20/mr2tachiyomi/files/5230531/mangarockbackups.zip)

**Comment by waicool20** [comment]
Copy a fresh json to your device, mightve gotten corrupted
