### ISSUE TITLE
databases folder in the directory

### ISSUE THREAD

**Issue by vadlannap** [waicool20/mr2tachiyomi#6]
I can't find it in my android device, there is only cache and files folder

**Comment by waicool20** [comment]
You got the wrong directory, the one you found is `sdcard:/Android/data/com.notabasement.mangarock.android.lotus/`

You need to go to `root:/data/data/com.notabasement.mangarock.android.lotus/databases`

**Comment by vadlannap** [comment]
Thank you :D
