### ISSUE TITLE
Conversion error due to empty Author field

### ISSUE THREAD

**Issue by TxXDRAGONXxT** [waicool20/mr2tachiyomi#7]
[mangarock.db.zip](https://github.com/waicool20/mr2tachiyomi/files/3608649/mangarock.db.zip)
hello i got an issue and it is that my favorites are all from mangarock 
but the program says unsupported source

[mr2tachiyomi.log](https://github.com/waicool20/mr2tachiyomi/files/3608642/mr2tachiyomi.log)

**Comment by waicool20** [comment]
Fixed in v1.2.2
