### ISSUE TITLE
License error while trying to restore backup json

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [waicool20/mr2tachiyomi#8]
I am getting the following error when I am restoring the backup json created by this tool in Tachiyomi.
`[Date Time] <manganame> - Value Manga is licensed at data of type java.lang.String cannot be converted to JSONObject`
While restoring, I got 43 errors and the error log is showing the above error statement for 43 of my favourited mangas. It seems like MR has removed some mangas from the website due to copyright strike. Is there a possible workaround for this.
[tachiyomi_restore.log.pdf](https://github.com/waicool20/mr2tachiyomi/files/3613409/tachiyomi_restore.log.pdf)

**Comment by waicool20** [comment]
Sadly no, tachiyomi doesnt have access to the removed material.
