### ISSUE TITLE
iam double clicking but it is not opening am i doing something wrong ?

### ISSUE THREAD

**Issue by aditbharadwaj** [waicool20/mr2tachiyomi#9]
iam double clicking the jar file but it aint opening only a text file generated in the same folder

**Comment by aditbharadwaj** [comment]
do i need the specific JDK ? bcoz i have jdk 11 already installed

**Comment by waicool20** [comment]
Which jdk do you have, oracle? it needs to come with javafx 8 not 11

**Comment by aditbharadwaj** [comment]
i will download javfx 8 . thnx

**Comment by waicool20** [comment]
Just fyi the oracle distribution of jdk8 comes with javafx8 pre-installed, if youre using something like openj9 youll need to work it out yourself, if you don't need gui you can use command line as well

**Comment by aditbharadwaj** [comment]
yep i got that I have jdk 11 installed I need to downgrade I suppose to 8.

Thanks

Regards,

Adit Bharadwaj
